/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, Interface } from "ethers-v6";
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_pair",
                type: "address",
            },
            {
                internalType: "address",
                name: "_router",
                type: "address",
            },
            {
                internalType: "address",
                name: "_WETH9",
                type: "address",
            },
            {
                internalType: "address",
                name: "_stakingRewards",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "amount0V1",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount1V1",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount0V2",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount1V2",
                type: "uint256",
            },
        ],
        name: "TestCalc",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokensToMigrate",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "amount0Min",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "amount1Min",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "to",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "deadline",
                type: "uint256",
            },
        ],
        name: "migrate",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class OrionMigrator__factory {
    static createInterface() {
        return new Interface(_abi);
    }
    static connect(address, runner) {
        return new Contract(address, _abi, runner);
    }
}
OrionMigrator__factory.abi = _abi;
export { OrionMigrator__factory };
